/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import Configurator.Connector;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author user name
 */
public class main_frame extends javax.swing.JFrame {
    
    private Connector connection = new Connector();
    /**
     * Creates new form main_frame
     */
    public main_frame() {
        initComponents();
        rpa();
    }
      public main_frame(String uname) {
        initComponents();
        lblwelcome.setText("Welcome "+uname);
        rpa();
    }
     
//AddProduct x = new AddProduct();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Addproduct = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        update = new javax.swing.JDialog();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfprice = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        tfquantity = new javax.swing.JSpinner();
        tfprn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        addquantf = new javax.swing.JSpinner();
        lbladdquan = new javax.swing.JLabel();
        btnquan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        tfkeyword = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNoofi = new javax.swing.JLabel();
        lblwelcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblload = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        Addproduct.setMinimumSize(new java.awt.Dimension(350, 350));

        javax.swing.GroupLayout AddproductLayout = new javax.swing.GroupLayout(Addproduct);
        Addproduct.setLayout(AddproductLayout);
        AddproductLayout.setHorizontalGroup(
            AddproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        AddproductLayout.setVerticalGroup(
            AddproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        jButton5.setText("Save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setText("Item Name:");

        tfprice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        tfprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpriceActionPerformed(evt);
            }
        });

        jLabel4.setText("Price:");

        tfquantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel5.setText("Quantity:");

        jLabel6.setText("id:");

        lblid.setText("id:");

        addquantf.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 10));

        lbladdquan.setText("Please Select How Many You will add");

        btnquan.setText("Add Quantity");
        btnquan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateLayout = new javax.swing.GroupLayout(update.getContentPane());
        update.getContentPane().setLayout(updateLayout);
        updateLayout.setHorizontalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(updateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateLayout.createSequentialGroup()
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfprn)
                            .addComponent(tfquantity)
                            .addComponent(tfprice)
                            .addGroup(updateLayout.createSequentialGroup()
                                .addComponent(lblid)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(updateLayout.createSequentialGroup()
                        .addComponent(lbladdquan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addquantf, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnquan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        updateLayout.setVerticalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfprn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(27, 27, 27)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbladdquan)
                    .addComponent(addquantf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnquan))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        tfkeyword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfkeywordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfkeywordKeyTyped(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Statistics"));

        jLabel2.setText("No of Items");

        lblNoofi.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblNoofi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNoofi)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        lblwelcome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblwelcome.setText("WELCOME!!!!");

        jLabel1.setText("SEARCH:");

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        tblload.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Product Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblload.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblload);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("ADD ITEMS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfkeyword, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblwelcome)
                    .addComponent(tfkeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
addproductf apf = new addproductf();
apf.setLocationRelativeTo(null);
apf.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AddProduct aps = new AddProduct();
        int selrow = tblload.getSelectedRow();
        
    if(selrow == -1){
        JOptionPane.showMessageDialog(rootPane, "Please Select A Row to be deleted","Error",JOptionPane.WARNING_MESSAGE);
    }else{
        String name = tblload.getValueAt(selrow, 1).toString();
         int x = JOptionPane.showConfirmDialog(rootPane, 
            "ARE YOU SURE YOU WANT TO DELETE THIS RECORD IT CANNOT BE RECOVERED",
            "CONFORMATION",JOptionPane.OK_CANCEL_OPTION);
        if(x == JOptionPane.OK_OPTION){
          int y = JOptionPane.showConfirmDialog(rootPane, "The Product "+name+" will be Deleted","Warning",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
            if(y == JOptionPane.YES_OPTION){
            String sid = tblload.getValueAt(selrow, 0).toString();
            aps.dproduct(sid);
            rpa();
    }
}
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         int row = tblload.getSelectedRow();
      if (row != -1){
        String id = tblload.getValueAt(row, 0).toString();
        String name = tblload.getValueAt(row, 1).toString();
        int quantity = Integer.parseInt(tblload.getValueAt(row, 2).toString());
        double price = Double.parseDouble(tblload.getValueAt(row, 3).toString());
        
        
        lblid.setText(id);
        tfprn.setText(name);
        tfquantity.setValue(quantity);
        tfprice.setValue(price);
        tfquantity.setEnabled(false);
        addquantf.setVisible(false);
        lbladdquan.setVisible(false);
        update.setSize(400,400);
        update.setLocationRelativeTo(null);
        update.setVisible(true);
        
      }else{
          JOptionPane.showMessageDialog(rootPane,"Please select a row to be updated","Np row Selected",JOptionPane.WARNING_MESSAGE);
      }
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     AddProduct ap = new AddProduct();
     String id = lblid.getText();
     String name = tfprn.getText();
    int quant = Integer.parseInt(tfquantity.getValue().toString());
    double price = Double.parseDouble(tfprice.getValue().toString());
     int x = ap.UpdateProduct(id, name, quant, price);
     if (x == 1){
         JOptionPane.showMessageDialog(rootPane, "Data Updated Successfully","Successfully",JOptionPane.INFORMATION_MESSAGE);
         rpa();
         update.setVisible(false);
     }else{
           JOptionPane.showMessageDialog(rootPane, "update Unsuccessful","warning",JOptionPane.WARNING_MESSAGE);
     }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tfpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpriceActionPerformed
        jButton2ActionPerformed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_tfpriceActionPerformed

    private void tfkeywordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfkeywordKeyReleased
     search(); // TODO add your handling code here:
    }//GEN-LAST:event_tfkeywordKeyReleased

    private void tfkeywordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfkeywordKeyTyped
     search();    // TODO add your handling code here:
    }//GEN-LAST:event_tfkeywordKeyTyped

    private void btnquanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquanActionPerformed
   int x = Integer.parseInt(tfquantity.getValue().toString());
   int y = Integer.parseInt(addquantf.getValue().toString());
   int z = 0;
    if(btnquan.getText() == "Add Quantity"){
         lbladdquan.setVisible(true);
         addquantf.setVisible(true);
         btnquan.setText("Save");
    }else{
        z = x+y;
         lbladdquan.setVisible(false);
         addquantf.setVisible(false);
         tfquantity.setValue(z);
         btnquan.setText("Add Quantity"); 
    }
    }//GEN-LAST:event_btnquanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_frame().setVisible(true);
            }
        });
    }
private void search(){
    String skey = tfkeyword.getText();
    int row = 0;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection(connection.getCon());
        String sql ="Select * from add_product where p_id like ? or p_name like ? ";
        PreparedStatement pstmt = con.prepareStatement(sql);
        pstmt.setString(1, "%"+skey+"%");
        pstmt.setString(2, "%"+skey+"%");
        ResultSet rs = pstmt.executeQuery();
        DefaultTableModel tbl = (DefaultTableModel) tblload.getModel();
        tbl.setRowCount(0);
        while(rs.next()){
            tbl.addRow(new Object[]{});
            tblload.setValueAt(rs.getString("p_id"), row, 0);
            tblload.setValueAt(rs.getString("p_name"), row, 1);
            tblload.setValueAt(rs.getString("p_quantity"), row, 2);
            tblload.setValueAt(rs.getString("p_price"), row, 3);
            row++;
        }
    }   catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(main_frame.class.getName()).log(Level.SEVERE, null, ex);
        }    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Addproduct;
    private javax.swing.JSpinner addquantf;
    private javax.swing.JButton btnquan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblNoofi;
    private javax.swing.JLabel lbladdquan;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblwelcome;
    public javax.swing.JTable tblload;
    private javax.swing.JTextField tfkeyword;
    private javax.swing.JFormattedTextField tfprice;
    private javax.swing.JTextField tfprn;
    private javax.swing.JSpinner tfquantity;
    private javax.swing.JDialog update;
    // End of variables declaration//GEN-END:variables
public void rpa(){
         int row = 0;
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection(connection.getCon());
        PreparedStatement pss = con.prepareStatement("select * from add_product order by p_id desc;");
        ResultSet rs = pss.executeQuery();
        DefaultTableModel tbl = (DefaultTableModel) tblload.getModel();
        while(rs.next()){
            tbl.addRow(new Object[]{});
            tblload.setValueAt(rs.getString("p_id"), row, 0);
            tblload.setValueAt(rs.getString("p_name"), row, 1);
            tblload.setValueAt(rs.getString("p_quantity"), row, 2);
            tblload.setValueAt(rs.getString("p_price"), row, 3);
            row++;
           
        }
lblNoofi.setText(String.valueOf(row));
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(AddProduct.class.getName()).log(Level.SEVERE, null, ex);
    }   

}
        
}